import { db } from "@/db";
import { tracks } from "@/db/schema";

async function main() {
  console.log("Seeding tracks...");

  await db.insert(tracks).values([
    {
      title: "Bohemian Rhapsody",
      artist: "Queen",
      albumName: "A Night at the Opera",
      lyricist: "Freddie Mercury",
      composer: "Freddie Mercury",
      duration: "5:55",
      publisher: "EMI",
      releaseYear: 1975,
      phonogramCatalogNumber: "EMI12345",
      trackCatalogNumber: "TRK001",
    },
    {
      title: "Imagine",
      artist: "John Lennon",
      albumName: "Imagine",
      lyricist: "John Lennon",
      composer: "John Lennon",
      duration: "3:03",
      publisher: "Apple Records",
      releaseYear: 1971,
      phonogramCatalogNumber: "APL12345",
      trackCatalogNumber: "TRK002",
    },
    {
      title: "Hotel California",
      artist: "Eagles",
      albumName: "Hotel California",
      lyricist: "Don Henley, Glenn Frey",
      composer: "Don Felder, Don Henley, Glenn Frey",
      duration: "6:30",
      publisher: "Asylum Records",
      releaseYear: 1976,
      phonogramCatalogNumber: "ASY12345",
      trackCatalogNumber: "TRK003",
    },
    {
      title: "Stairway to Heaven",
      artist: "Led Zeppelin",
      albumName: "Led Zeppelin IV",
      lyricist: "Robert Plant",
      composer: "Jimmy Page",
      duration: "8:02",
      publisher: "Atlantic Records",
      releaseYear: 1971,
      phonogramCatalogNumber: "ATL12345",
      trackCatalogNumber: "TRK004",
    },
    {
      title: "Smells Like Teen Spirit",
      artist: "Nirvana",
      albumName: "Nevermind",
      lyricist: "Kurt Cobain",
      composer: "Kurt Cobain",
      duration: "5:01",
      publisher: "DGC",
      releaseYear: 1991,
      phonogramCatalogNumber: "DGC12345",
      trackCatalogNumber: "TRK005",
    },
    {
      title: "Billie Jean",
      artist: "Michael Jackson",
      albumName: "Thriller",
      lyricist: "Michael Jackson",
      composer: "Michael Jackson",
      duration: "4:54",
      publisher: "Epic",
      releaseYear: 1982,
      phonogramCatalogNumber: "EPC12345",
      trackCatalogNumber: "TRK006",
    },
    {
      title: "Hey Jude",
      artist: "The Beatles",
      albumName: "Hey Jude",
      lyricist: "Paul McCartney, John Lennon",
      composer: "Paul McCartney, John Lennon",
      duration: "7:11",
      publisher: "Apple Records",
      releaseYear: 1968,
      phonogramCatalogNumber: "APL12346",
      trackCatalogNumber: "TRK007",
    },
    {
      title: "Like a Rolling Stone",
      artist: "Bob Dylan",
      albumName: "Highway 61 Revisited",
      lyricist: "Bob Dylan",
      composer: "Bob Dylan",
      duration: "6:13",
      publisher: "Columbia",
      releaseYear: 1965,
      phonogramCatalogNumber: "COL12345",
      trackCatalogNumber: "TRK008",
    },
    {
      title: "Sweet Child o' Mine",
      artist: "Guns N' Roses",
      albumName: "Appetite for Destruction",
      lyricist: "Axl Rose",
      composer: "Slash, Izzy Stradlin, Duff McKagan, Steven Adler",
      duration: "5:56",
      publisher: "Geffen",
      releaseYear: 1987,
      phonogramCatalogNumber: "GEF12345",
      trackCatalogNumber: "TRK009",
    },
    {
      title: "Wonderwall",
      artist: "Oasis",
      albumName: "(What's the Story) Morning Glory?",
      lyricist: "Noel Gallagher",
      composer: "Noel Gallagher",
      duration: "4:18",
      publisher: "Creation Records",
      releaseYear: 1995,
      phonogramCatalogNumber: "CRE12345",
      trackCatalogNumber: "TRK010",
    },
    {
      title: "Beat It",
      artist: "Michael Jackson",
      albumName: "Thriller",
      lyricist: "Michael Jackson",
      composer: "Michael Jackson",
      duration: "4:18",
      publisher: "Epic",
      releaseYear: 1982,
      phonogramCatalogNumber: "EPC12346",
      trackCatalogNumber: "TRK021",
    },
    {
      title: "Take On Me",
      artist: "A-ha",
      albumName: "Hunting High and Low",
      lyricist: "Morten Harket",
      composer: "Magne Furuholmen, Paul Waaktaar-Savoy",
      duration: "3:46",
      publisher: "Warner Bros.",
      releaseYear: 1985,
      phonogramCatalogNumber: "WB12347",
      trackCatalogNumber: "TRK022",
    },
    {
      title: "With or Without You",
      artist: "U2",
      albumName: "The Joshua Tree",
      lyricist: "Bono",
      composer: "U2",
      duration: "4:56",
      publisher: "Island Records",
      releaseYear: 1987,
      phonogramCatalogNumber: "ISL12348",
      trackCatalogNumber: "TRK023",
    },
    {
      title: "Yesterday",
      artist: "The Beatles",
      albumName: "Help!",
      lyricist: "Paul McCartney",
      composer: "Paul McCartney",
      duration: "2:05",
      publisher: "Parlophone",
      releaseYear: 1965,
      phonogramCatalogNumber: "PAR12349",
      trackCatalogNumber: "TRK024",
    },
    {
      title: "Radioactive",
      artist: "Imagine Dragons",
      albumName: "Night Visions",
      lyricist: "Dan Reynolds",
      composer: "Imagine Dragons",
      duration: "3:06",
      publisher: "Interscope",
      releaseYear: 2012,
      phonogramCatalogNumber: "INT12350",
      trackCatalogNumber: "TRK025",
    },
    {
      title: "Rolling in the Deep",
      artist: "Adele",
      albumName: "21",
      lyricist: "Adele",
      composer: "Adele, Paul Epworth",
      duration: "3:49",
      publisher: "XL Recordings",
      releaseYear: 2010,
      phonogramCatalogNumber: "XL12351",
      trackCatalogNumber: "TRK026",
    },
    {
      title: "Somebody That I Used to Know",
      artist: "Gotye feat. Kimbra",
      albumName: "Making Mirrors",
      lyricist: "Wouter De Backer",
      composer: "Wouter De Backer",
      duration: "4:04",
      publisher: "Eleven",
      releaseYear: 2011,
      phonogramCatalogNumber: "ELE12352",
      trackCatalogNumber: "TRK027",
    },
    {
      title: "Can't Stop",
      artist: "Red Hot Chili Peppers",
      albumName: "By the Way",
      lyricist: "Anthony Kiedis",
      composer: "Flea, John Frusciante, Chad Smith",
      duration: "4:29",
      publisher: "Warner Bros.",
      releaseYear: 2002,
      phonogramCatalogNumber: "WB12353",
      trackCatalogNumber: "TRK028",
    },
    {
      title: "Mr. Brightside",
      artist: "The Killers",
      albumName: "Hot Fuss",
      lyricist: "Brandon Flowers",
      composer: "The Killers",
      duration: "3:42",
      publisher: "Island Records",
      releaseYear: 2003,
      phonogramCatalogNumber: "ISL12354",
      trackCatalogNumber: "TRK029",
    },
    {
      title: "Seven Nation Army",
      artist: "The White Stripes",
      albumName: "Elephant",
      lyricist: "Jack White",
      composer: "Jack White",
      duration: "3:51",
      publisher: "V2",
      releaseYear: 2003,
      phonogramCatalogNumber: "V212355",
      trackCatalogNumber: "TRK030",
    },
    {
      title: "Let It Be",
      artist: "The Beatles",
      albumName: "Let It Be",
      lyricist: "Paul McCartney",
      composer: "Paul McCartney",
      duration: "4:03",
      publisher: "Apple Records",
      releaseYear: 1970,
      phonogramCatalogNumber: "APL12356",
      trackCatalogNumber: "TRK031",
    },
    {
      title: "Heroes",
      artist: "David Bowie",
      albumName: '"Heroes"',
      lyricist: "David Bowie",
      composer: "David Bowie, Brian Eno",
      duration: "3:35",
      publisher: "RCA",
      releaseYear: 1977,
      phonogramCatalogNumber: "RCA12357",
      trackCatalogNumber: "TRK032",
    },
    {
      title: "Don't Stop Believin'",
      artist: "Journey",
      albumName: "Escape",
      lyricist: "Steve Perry",
      composer: "Jonathan Cain, Neal Schon",
      duration: "4:11",
      publisher: "Columbia",
      releaseYear: 1981,
      phonogramCatalogNumber: "COL12358",
      trackCatalogNumber: "TRK033",
    },
    {
      title: "Back in Black",
      artist: "AC/DC",
      albumName: "Back in Black",
      lyricist: "Brian Johnson",
      composer: "Angus Young, Malcolm Young",
      duration: "4:15",
      publisher: "Atlantic Records",
      releaseYear: 1980,
      phonogramCatalogNumber: "ATL12359",
      trackCatalogNumber: "TRK034",
    },
    {
      title: "Boulevard of Broken Dreams",
      artist: "Green Day",
      albumName: "American Idiot",
      lyricist: "Billie Joe Armstrong",
      composer: "Green Day",
      duration: "4:20",
      publisher: "Reprise",
      releaseYear: 2004,
      phonogramCatalogNumber: "REP12360",
      trackCatalogNumber: "TRK035",
    },
    {
      title: "Africa",
      artist: "Toto",
      albumName: "Toto IV",
      lyricist: "David Paich",
      composer: "Jeff Porcaro",
      duration: "4:55",
      publisher: "Columbia",
      releaseYear: 1982,
      phonogramCatalogNumber: "COL12361",
      trackCatalogNumber: "TRK036",
    },
    {
      title: "Smack That",
      artist: "Akon feat. Eminem",
      albumName: "Konvicted",
      lyricist: "Akon, Eminem",
      composer: "Akon, Eminem",
      duration: "3:32",
      publisher: "SRC",
      releaseYear: 2006,
      phonogramCatalogNumber: "SRC12362",
      trackCatalogNumber: "TRK037",
    },
    {
      title: "Counting Stars",
      artist: "OneRepublic",
      albumName: "Native",
      lyricist: "Ryan Tedder",
      composer: "Ryan Tedder",
      duration: "4:17",
      publisher: "Mosley",
      releaseYear: 2013,
      phonogramCatalogNumber: "MOS12363",
      trackCatalogNumber: "TRK038",
    },
    {
      title: "Blinding Lights",
      artist: "The Weeknd",
      albumName: "After Hours",
      lyricist: "Abel Tesfaye",
      composer: "Max Martin, Oscar Holter",
      duration: "3:20",
      publisher: "XO",
      releaseYear: 2020,
      phonogramCatalogNumber: "XO12364",
      trackCatalogNumber: "TRK039",
    },
    {
      title: "Shape of You",
      artist: "Ed Sheeran",
      albumName: "÷ (Divide)",
      lyricist: "Ed Sheeran",
      composer: "Ed Sheeran, Steve Mac",
      duration: "3:53",
      publisher: "Asylum Records",
      releaseYear: 2017,
      phonogramCatalogNumber: "ASY12365",
      trackCatalogNumber: "TRK040",
    },
  ]);

  console.log("Seeding completed!");
}

main();
