export const dataTableConfig = {
  textOperators: [
    { label: "Zawiera", value: "iLike" as const },
    { label: "Nie zawiera", value: "notILike" as const },
    { label: "Jest", value: "eq" as const },
    { label: "Nie jest", value: "ne" as const },
    { label: "Jest puste", value: "isEmpty" as const },
    { label: "Nie jest puste", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "Jest", value: "eq" as const },
    { label: "Nie jest", value: "ne" as const },
    { label: "Jest mniejsze niż", value: "lt" as const },
    { label: "Jest mniejsze lub równe", value: "lte" as const },
    { label: "Jest większe niż", value: "gt" as const },
    { label: "Jest większe lub równe", value: "gte" as const },
    { label: "Jest pomiędzy", value: "isBetween" as const },
    { label: "Jest puste", value: "isEmpty" as const },
    { label: "Nie jest puste", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "Jest", value: "eq" as const },
    { label: "Nie jest", value: "ne" as const },
    { label: "Jest przed", value: "lt" as const },
    { label: "Jest po", value: "gt" as const },
    { label: "Jest w dniu lub przed", value: "lte" as const },
    { label: "Jest w dniu lub po", value: "gte" as const },
    { label: "Jest pomiędzy", value: "isBetween" as const },
    { label: "Jest względem dzisiaj", value: "isRelativeToToday" as const },
    { label: "Jest puste", value: "isEmpty" as const },
    { label: "Nie jest puste", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "Jest", value: "eq" as const },
    { label: "Nie jest", value: "ne" as const },
    { label: "Jest puste", value: "isEmpty" as const },
    { label: "Nie jest puste", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "Zawiera dowolne z", value: "inArray" as const },
    { label: "Nie zawiera żadnego z", value: "notInArray" as const },
    { label: "Jest puste", value: "isEmpty" as const },
    { label: "Nie jest puste", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "Jest", value: "eq" as const },
    { label: "Nie jest", value: "ne" as const },
  ],
  sortOrders: [
    { label: "Rosnąco", value: "asc" as const },
    { label: "Malejąco", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
} as const;

export type DataTableConfig = typeof dataTableConfig;
